config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :events do
    resources :event_registrations, only: %i[create destroy]
  end
  get 'events/:id/modal', to: 'events#modal', as: 'event_modal'

  resources :users, only: [:show]

  resources :users do
    get 'events', to: 'events#users_events'
  end

  root "events#index"
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :event_registrations, dependent: :destroy
  has_many :users, through: :event_registrations


  belongs_to :organizer, foreign_key: :organizer_id, class_name: "User"

  validates :title, presence: true
  validates :description, presence: true
  validates :location, presence: true
  validates :date, presence: true
  validate :date_cannot_be_in_the_past


  def date_cannot_be_in_the_past
    if date.present? && date < DateTime.now
      errors.add(:date, "не может быть в прошлом")
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :set_event, only: %i[ show edit update destroy ]
  before_action :ensure_profile_complete, only: [:new, :create]


  def index
    @events = Event.all
  end

  def show
    respond_to do |format|
      format.html # стандартный шаблон show
      format.js { render partial: 'events/event_modal' } # рендеринг частичного шаблона для модального окна
    end
  end

  def create
    @event = Event.new(event_params)
    @event.organizer = current_user

    if @event.save
      redirect_to @event, notice: "Мероприятие создано!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def new
    @event = Event.new
  end

  def update
    if @event.update(event_params)
      redirect_to @event, notice: "Мероприятие обновлено"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @event.destroy
    redirect_to events_url, notice: "Мероприятие удалено"
  end

  def modal
    @event = Event.find(params[:id])
    render partial: 'events/event_modal', locals: { event: @event }
  end

  def users_events
    @user = User.find(params[:user_id])
    @events = @user.organized_events
  end


  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :description, :location, :date, :price)
  end

  def ensure_profile_complete
    unless current_user.profile_complete?
      redirect_to edit_user_registration_path, alert: 'Пожалуйста, заполните профиль перед созданием мероприятия.'
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event_modal.html.erb
<div class="modal-event-details">
  <h2><%= event.title %></h2>
  <% if event.image.attached? %>
    <%= image_tag event.image, alt: event.title, class: "modal-event-image" %>
  <% end %>
  <p><%= event.description %></p>
  <p><strong>Место:</strong> <%= event.location %></p>
  <p><strong>Дата:</strong> <%= l(event.date, format: :long) %></p>
  <p><strong>Организатор:</strong> <%= event.organizer.email %></p>
</div>

app/views/events/edit.html.erb
<h1>Редактировать мероприятие</h1>
<%= stylesheet_link_tag 'events_edit', media: 'all' %>

<%= form_with(model: @event, local: true) do |form| %>
  <% if @event.errors.any? %>
    <div>
      <h2>Ошибки:</h2>
      <ul>
        <% @event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, 'Название' %><br>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, 'Описание' %><br>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :location, 'Место' %><br>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.label :date, 'Дата и время' %><br>
    <%= form.datetime_select :date %>
  </div>

  <div>
    <%= form.label :price, 'Цена' %><br>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.submit 'Обновить мероприятие' %>
  </div>
<% end %>

<%= link_to 'Назад к списку', events_path %>

app/views/events/index.html.erb
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Мероприятия</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <!-- Подключение стилей -->
  <%= stylesheet_link_tag 'events_index', media: 'all' %>
  <%= javascript_include_tag 'application' %>

  <!-- Подключение Font Awesome для иконок -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
</head>
<body>

<main class="main-content">
  <!-- Кнопка "Создать мероприятие" -->
  <% if user_signed_in? %>
    <div class="create-event-button">
      <%= link_to 'Создать мероприятие', new_event_path, class: 'btn btn-create-event' %>
    </div>
  <% end %>

  <!-- Сетка мероприятий -->
  <div class="events-grid">
    <% @events.each do |event| %>
      <div class="event-card" data-event-id="<%= event.id %>">
<!--        <div class="event-image-container">-->
          <%# if event.image.attached? %>
            <%#= image_tag event.image, class: 'event-image', alt: event.title %>
          <%# else %>
            <%#= image_tag 'placeholder.jpg', class: 'event-image', alt: 'Placeholder Image' %>
          <%# end %>
<!--        </div>-->
        <div class="event-details">
          <h2 class="event-title">
            <%= link_to event.title, event, class: 'event-link' %>
          </h2>
          <div class="event-meta">
            <p><i class="fas fa-map-marker-alt"></i> <%= event.location %></p>
            <p><i class="fas fa-calendar-alt"></i> <%= l(event.date, format: :long) %></p>
            <p><i class="fas fa-user"></i> <%= event.organizer.email %></p>
            <% if event.price.nil? || event.price == 0 %>
              <p><i class="fas fa-dollar-sign"></i> Бесплатно</p>
            <% else %>
              <p><i class="fas fa-dollar-sign"></i> <%= event.price %> ₽</p>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</main>

<!-- Модальное окно -->
<div id="event-modal" class="modal">
  <div class="modal-content">
    <span class="modal-close">&times;</span>
    <div id="modal-body">
      <!-- Динамическое содержимое мероприятия -->
    </div>
  </div>
</div>

</body>
</html>

app/views/events/new.html.erb
<%= stylesheet_link_tag 'events_new', media: 'all' %>

<div class="event-form-container">
  <h1 class="add-event">Создание мероприятия</h1>

  <%= form_with(model: @event, local: true, html: { class: 'needs-validation', novalidate: true }) do |form| %>
    <% if @event.errors.any? %>
      <div class="alert alert-danger">
        <h4 class="alert-heading">Возникли ошибки при сохранении:</h4>
        <ul>
          <% @event.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :title, 'Название' %>
      <%= form.text_field :title, required: true, class: 'form-control' %>
      <div class="invalid-feedback">
        Пожалуйста, введите название мероприятия.
      </div>
    </div>

    <div class="form-group">
      <%= form.label :description, 'Описание' %>
      <%= form.text_area :description, rows: 5, required: true, class: 'form-control' %>
      <div class="invalid-feedback">
        Пожалуйста, введите описание мероприятия.
      </div>
    </div>

    <div class="form-group">
      <%= form.label :location, 'Место' %>
      <%= form.text_field :location, required: true, class: 'form-control' %>
      <div class="invalid-feedback">
        Пожалуйста, укажите место проведения.
      </div>
    </div>

    <div class="form-group">
      <%= form.label :date, 'Дата и время' %>
      <%= form.datetime_field :date, required: true, class: 'form-control' %>
      <div class="invalid-feedback">
        Пожалуйста, выберите дату и время.
      </div>
    </div>

    <div class="form-group">
      <%= form.label :price, 'Цена' %>
      <%= form.number_field :price, step: 0.01, required: true, class: 'form-control' %>
      <div class="invalid-feedback">
        Пожалуйста, укажите цену.
      </div>
    </div>

<!--    <div class="form-group">-->
      <%#= form.label :image, 'Изображение' %>
      <%#= form.file_field :image, class: 'form-control' %>
<!--    </div>-->

    <div class="form-group">
      <%= form.submit 'Создать мероприятие', class: 'btn btn-primary' %>
    </div>
  <% end %>

  <%= link_to 'Назад к списку', events_path, class: 'btn-link' %>
</div>

app/views/events/show.html.erb
<%= stylesheet_link_tag 'events_show', media: 'all' %>

<main class="main-content">
  <!-- Новый заголовок мероприятия -->
  <header class="event-header">
    <div class="event-header-content">
      <div class="event-header-overlay">
        <h1 class="event-title"><%= @event.title %></h1>
        <p class="event-date-location-price">
          <span class="event-date"><i class="fas fa-calendar-alt"></i> <%= l(@event.date, format: :long) %></span>
          <span class="event-location"><i class="fas fa-map-marker-alt"></i> <%= @event.location %></span>
          <span class="event-price"><i class="fas fa-dollar-sign"></i> <%= @event.price.presence || 0 %> ₽ </span>
        </p>
      </div>
    </div>
  </header>

  <!-- Контейнер с деталями мероприятия -->
  <div class="event-details-container">
    <!-- Описание мероприятия -->
    <section class="event-description-section">
      <h2>Описание</h2>
      <p class="event-description"><%= @event.description %></p>
    </section>

    <!-- Организатор мероприятия -->
    <section class="event-organizer-section">
      <h2>Организатор</h2>
      <p><i class="fas fa-user"></i>
        <%= link_to (@event.organizer.name.presence || @event.organizer.email), user_events_path(@event.organizer) %>
      </p>
    </section>

    <!-- Зарегистрированные пользователи -->
    <section class="event-registered-users-section">
      <h2>Участники</h2>
      <% if @event.users.any? %>
        <ul class="registered-users-list">
          <% @event.users.each do |user| %>
            <li><i class="fas fa-user"></i>   <%= link_to (user.name.presence || user.email), user_events_path(user), class: 'user-link' %>
            </li>
          <% end %>
        </ul>
      <% else %>
        <p>На это мероприятие пока никто не зарегистрировался.</p>
      <% end %>
    </section>

    <!-- Кнопки действий -->
    <div class="event-actions">
      <% if user_signed_in? && current_user == @event.organizer %>
        <%= link_to 'Редактировать', edit_event_path(@event), class: 'btn btn-edit' %>
        <%= button_to 'Удалить', @event, method: :delete, data: { confirm: 'Вы уверены?' }, class: 'btn btn-delete' %>
        <%else %>
        <% if user_signed_in? && @event.users.include?(current_user) %>
          <%= button_to 'Отменить регистрацию', event_event_registration_path(@event, current_user.event_registrations.find_by(event_id: @event.id)), method: :delete, class: 'btn btn-cancel' %>
        <% else %>
          <%= button_to 'Записаться', event_event_registrations_path(@event), method: :post, class: 'btn btn-register' %>
        <% end %>
        <% end %>

    </div>

    <!-- Ссылка "Назад к списку" -->
    <div class="back-link">
      <%= link_to 'Назад к списку', events_path, class: 'btn btn-back' %>
    </div>
  </div>
</main>

app/views/events/users_events.html.erb
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <title>Мероприятия пользователя</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'events_index', media: 'all' %>
  <%= javascript_include_tag 'application' %>

  <!-- Подключение Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
</head>
<body>

<% if current_user.id == @user.id %>
  <h1 class="header-title" style="color: #434343">Мероприятия, которые вы организовали</h1>
<% else %>
  <h1 class="header-title" style="color: #434343">Мероприятия, которые организовал(а) <%= @user.name %></h1>
<% end %>  <main class="main-content">
    <div class="events-grid">
      <% if @events.any? %>
        <% @events.each do |event| %>
          <div class="event-card" data-event-id="<%= event.id %>">
            <div class="event-details">
              <h2 class="event-title"><%= link_to event.title, event, class: "event-link" %></h2>
              <div class="event-meta">
                <p><i class="fas fa-map-marker-alt"></i> <%= event.location %></p>
                <p><i class="fas fa-calendar-alt"></i> <%= l(event.date, format: :long) %></p>
                <p><i class="fas fa-user"></i>  <%= event.organizer.email %></p>
                <% if event.price.nil? || event.price == 0 %>
                  <p><i class="fas fa-dollar-sign"></i> Бесплатно</p>
                <% else %>
                  <p><i class="fas fa-dollar-sign"></i> <%= event.price %> ₽</p>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      <% else %>
        <p>Пока пусто(</p>
      <% end %>
    </div>
  </main>

<!-- Модальное окно -->
<div id="event-modal" class="modal">
  <div class="modal-content">
    <span class="modal-close">&times;</span>
    <div id="modal-body">
      <!-- Контент мероприятия будет загружаться сюда -->
    </div>
  </div>
</div>
</body>
</html>